# Generated by Django 4.2.11 on 2026-03-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('prize_won', models.IntegerField(default=0)),
                ('kills', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('rank_points_awarded', models.IntegerField(default=0)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'results',
                'ordering': ['tournament', 'position'],
                'unique_together': {('tournament', 'position')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(choices=[('ROUND_64', 'Round of 64'), ('ROUND_32', 'Round of 32'), ('ROUND_16', 'Round of 16'), ('QUARTER', 'Quarter Final'), ('SEMI', 'Semi Final'), ('THIRD_PLACE', 'Third Place Match'), ('FINAL', 'Grand Final')], max_length=15)),
                ('match_number', models.IntegerField()),
                ('bracket_position', models.IntegerField(default=0)),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('server_details', models.CharField(blank=True, max_length=200)),
                ('room_id', models.CharField(blank=True, max_length=50)),
                ('room_password', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='matches.match')),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player1', to='players.player')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player2', to='players.player')),
                ('team1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team1', to='teams.team')),
                ('team2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_team2', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('winner_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='players.player')),
                ('winner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='teams.team')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'db_table': 'matches',
                'ordering': ['round_name', 'match_number'],
                'unique_together': {('tournament', 'round_name', 'match_number')},
            },
        ),
    ]
