# Generated by Django 4.2.11 on 2026-03-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('tag', models.CharField(help_text='Short team tag e.g. NSR', max_length=10)),
                ('game', models.CharField(choices=[('BGMI', 'BGMI'), ('VALORANT', 'Valorant'), ('COD', 'Call of Duty Mobile'), ('FREE_FIRE', 'Free Fire'), ('CS2', 'Counter-Strike 2')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='team_banners/')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('rank_points', models.IntegerField(default=0)),
                ('is_recruiting', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='captained_team', to='players.player')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
                'ordering': ['-rank_points'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CAPTAIN', 'Captain'), ('IGL', 'In-Game Leader'), ('FRAGGER', 'Fragger'), ('SUPPORT', 'Support'), ('SCOUT', 'Scout'), ('SNIPER', 'Sniper'), ('SUBSTITUTE', 'Substitute'), ('MEMBER', 'Member')], default='MEMBER', max_length=15)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_membership', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'db_table': 'team_members',
                'unique_together': {('team', 'player')},
            },
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CAPTAIN', 'Captain'), ('IGL', 'In-Game Leader'), ('FRAGGER', 'Fragger'), ('SUPPORT', 'Support'), ('SCOUT', 'Scout'), ('SNIPER', 'Sniper'), ('SUBSTITUTE', 'Substitute'), ('MEMBER', 'Member')], default='MEMBER', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('message', models.TextField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='players.player')),
                ('invited_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invites', to='players.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='teams.team')),
            ],
            options={
                'db_table': 'team_invites',
                'unique_together': {('team', 'invited_player')},
            },
        ),
    ]
