# Generated by Django 4.2.11 on 2026-03-09 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('game', models.CharField(choices=[('BGMI', 'BGMI'), ('VALORANT', 'Valorant'), ('COD', 'Call of Duty Mobile'), ('FREE_FIRE', 'Free Fire'), ('CS2', 'Counter-Strike 2'), ('FIFA', 'FIFA / EA FC'), ('CHESS', 'Chess Online')], max_length=20)),
                ('mode', models.CharField(choices=[('SOLO', 'Solo'), ('DUO', 'Duo'), ('SQUAD', 'Squad (4 players)'), ('TEAM5', 'Team (5 players)')], default='SOLO', max_length=10)),
                ('description', models.TextField()),
                ('rules', models.TextField(blank=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='tournament_banners/')),
                ('entry_fee', models.IntegerField(default=0, help_text='Entry fee in INR (0 = free)')),
                ('max_players', models.IntegerField(default=64)),
                ('registration_deadline', models.DateTimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('match_time', models.TimeField(blank=True, null=True)),
                ('prize_pool', models.IntegerField(default=0)),
                ('first_prize', models.IntegerField(default=0)),
                ('second_prize', models.IntegerField(default=0)),
                ('third_prize', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('REGISTRATION_OPEN', 'Registration Open'), ('REGISTRATION_CLOSED', 'Registration Closed'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
                'db_table': 'tournaments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Payment Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('DISQUALIFIED', 'Disqualified')], default='PENDING', max_length=15)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('seed_number', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='players.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_registrations', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'db_table': 'registrations',
                'ordering': ['registered_at'],
                'unique_together': {('player', 'tournament')},
            },
        ),
    ]
