# Generated by Django 4.2.11 on 2026-03-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='OVERALL', max_length=15)),
                ('rank', models.IntegerField()),
                ('rank_points', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('season', models.CharField(default='Season 1', max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Leaderboard Entry',
                'verbose_name_plural': 'Team Leaderboard',
                'db_table': 'team_leaderboard',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OVERALL', 'Overall'), ('BGMI', 'BGMI'), ('VALORANT', 'Valorant'), ('COD', 'Call of Duty Mobile'), ('FREE_FIRE', 'Free Fire'), ('CS2', 'Counter-Strike 2')], default='OVERALL', max_length=15)),
                ('rank', models.IntegerField()),
                ('rank_points', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_kills', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('tournament_wins', models.IntegerField(default=0)),
                ('season', models.CharField(default='Season 1', max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='players.player')),
            ],
            options={
                'verbose_name': 'Leaderboard Entry',
                'verbose_name_plural': 'Leaderboard',
                'db_table': 'leaderboard',
                'ordering': ['rank'],
                'unique_together': {('player', 'category', 'season')},
            },
        ),
    ]
