# Generated by Django 4.2.11 on 2026-03-09 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ign', models.CharField(help_text='Your display name in the game', max_length=50, verbose_name='In-Game Name')),
                ('game_id', models.CharField(help_text='Your unique game ID or UID', max_length=100, verbose_name='Game ID / UID')),
                ('primary_game', models.CharField(choices=[('BGMI', 'BGMI (Battlegrounds Mobile India)'), ('VALORANT', 'Valorant'), ('COD', 'Call of Duty Mobile'), ('FREE_FIRE', 'Free Fire'), ('CS2', 'Counter-Strike 2'), ('FIFA', 'FIFA / EA FC'), ('CHESS', 'Chess Online'), ('POKEMON', 'Pokemon Unite')], default='BGMI', max_length=20)),
                ('secondary_game', models.CharField(blank=True, choices=[('BGMI', 'BGMI (Battlegrounds Mobile India)'), ('VALORANT', 'Valorant'), ('COD', 'Call of Duty Mobile'), ('FREE_FIRE', 'Free Fire'), ('CS2', 'Counter-Strike 2'), ('FIFA', 'FIFA / EA FC'), ('CHESS', 'Chess Online'), ('POKEMON', 'Pokemon Unite')], max_length=20, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('discord_id', models.CharField(blank=True, max_length=100)),
                ('instagram_handle', models.CharField(blank=True, max_length=100)),
                ('total_kills', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('total_matches', models.IntegerField(default=0)),
                ('tournament_wins', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rank_points', models.IntegerField(default=0)),
                ('tier', models.CharField(choices=[('Recruit', '🎖 Recruit'), ('Bronze', '🥉 Bronze'), ('Silver', '🥈 Silver'), ('Gold', '🥇 Gold'), ('Platinum', '💎 Platinum'), ('Diamond', '💠 Diamond'), ('Master', '👑 Master'), ('Legend', '🏆 Legend')], default='Recruit', max_length=20)),
                ('is_available', models.BooleanField(default=True, help_text='Available for team recruitment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player Profile',
                'verbose_name_plural': 'Player Profiles',
                'db_table': 'players',
                'ordering': ['-rank_points'],
            },
        ),
    ]
